#!/bin/bash

original_window=$1

choice=$(find ${HOME}/.kube/config ${HOME}/code/kubeconfigs -type f |fzf)
cmd=$(echo export\\ KUBECONFIG=${choice} Enter)

tmux neww "tmux send-key -t ${original_window} ${cmd}"
